/**
 * Server Side Rendering
 */
import { APIGatewayEvent } from "aws-lambda";
import * as React from "react";
import { renderToString } from "react-dom/server";
import fetch from "node-fetch";

import App from "../App";
import ConfigContext from "../components/ConfigContext";
import config from "./config";
import html from "./html";
import { Stats } from "./types";

/**
 * Server-side rendering
 */
export default async function render(_event: APIGatewayEvent): Promise<string> {
  // The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)

  const response = await fetch("https://app.sproutsocial.com/api/hv/groups/698320/messages/new/chart/", {
    "headers": {
      "accept": "application/json, text/javascript, */*",
      "accept-language": "en-US,en;q=0.9,fr;q=0.8",
      "content-type": "application/x-www-form-urlencoded",
      "sec-ch-ua": "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"",
      "sec-ch-ua-mobile": "?0",
      "sec-ch-ua-platform": "\"macOS\"",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-origin",
      "x-requested-with": "XMLHttpRequest",
      "cookie": "_gcl_au=1.1.1292858715.1667483618; _ga=GA1.3.538677281.1667483618; _mkto_trk=id:501-PTW-938&token:_mch-sproutsocial.com-1667483618020-52709; __zlcmid=1CllLhIqvNwXkL9; sprout-session=1604561%7Ccfe74fdfa788ec5ed7b1f195c524281761b0039a%7C; fs_cid=1.0; _ga_JNT9S8XFJD=GS1.1.1668728434.3.0.1668728434.0.0.0; intercom-device-id-ghwe0see=03d81549-35d7-4732-ab49-34c15a0872ad; intercom-device-id-ohku3rnz=6ed94354-97e9-4f69-aa10-7dc6fb5a63e4; _gid=GA1.2.1660923885.1669643386; DriftPlaybook=B; _rdt_uuid=1669727407356.2cfbfd55-a31b-4a09-809f-1fb1ebe179a1; _fbp=fb.1.1669727407438.918732975; _hjid=af3634ce-0f1e-4796-b2c2-d20b500d1e86; ss_uuid=2b415c83-480c-4a68-93d2-983d4682b7ba; ss_firstVisit=%7B%22adExtension%22%3A%22%22%2C%22browser%22%3A%22Chrome%20107.0%22%2C%22campaign%22%3A%22direct%22%2C%22content%22%3A%22%22%2C%22creative%22%3A%22%22%2C%22device%22%3A%22%22%2C%22landingPage%22%3A%22https%3A%2F%2Fsproutsocial.com%2Fcareers%2F%22%2C%22location%22%3A%22%22%2C%22matchType%22%3A%22%22%2C%22medium%22%3A%22none%22%2C%22source%22%3A%22direct%22%2C%22ss_uuid%22%3A%222b415c83-480c-4a68-93d2-983d4682b7ba%22%2C%22term%22%3A%22%22%2C%22userDevice%22%3A%22desktop%22%2C%22visitorID%22%3A%22538677281.1667483618%22%2C%22pardotVisitorID%22%3A%22151516311%22%2C%22optimizelyEndUserId%22%3A%22%22%2C%22timestamp%22%3A1669727407657%7D; _hjSessionUser_266032=eyJpZCI6IjQwZmQwMmRmLTc1MmYtNTFmNS1hMmY3LTYxZTM5N2Q3MDAyOSIsImNyZWF0ZWQiOjE2Njk3Mjc0MDc2MjgsImV4aXN0aW5nIjp0cnVlfQ==; drift_aid=51c09cb7-1e37-4537-a033-5868660a15c8; driftt_aid=51c09cb7-1e37-4537-a033-5868660a15c8; fs_uid=#RWAAW#6077137528967168:5509921541345280:::#/1700692811; _gid=GA1.3.1660923885.1669643386; _ga_R3D7HYPDX2=GS1.1.1669905810.7.0.1669905810.0.0.0; ci_csrf_token=e719a8b877f24710197cacefde345d5b; app_language=en-us; _uetsid=d2b3b620718511edaaf7c7b050c60144; _uetvid=a29b18c014dd11ed917bd90803e30a83; _ga=GA1.2.538677281.1667483618; bookmarklet-session=1604561%7Ccfe74fdfa788ec5ed7b1f195c524281761b0039a%7C; ci_csrf_bookmarklet_token=e719a8b877f24710197cacefde345d5b; _ga_WY9TEC8W6X=GS1.1.1669907582.11.1.1669907596.0.0.0; storagepreloaded=cbf6f51d89a6fce5703ba4dfb584312b39a94a1f__698320__false; mp_ab42544502181716ca5ba85d7bd75da3_mixpanel=%7B%22distinct_id%22%3A%20%221604561_415272%22%2C%22%24device_id%22%3A%20%221843de8930e3e-03f05b932da8b9-18525635-1aeaa0-1843de8930f125%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Flocal.int.sproutsocial.com%2Fprofile%2Ftwitter%2F1305898429747539969%2Fhistory%2F7092967%2F%3Fgid%3D698320%22%2C%22%24initial_referring_domain%22%3A%20%22local.int.sproutsocial.com%22%2C%22%24user_id%22%3A%20%221604561_415272%22%2C%22Customer%20ID%22%3A%20415272%2C%22Group%20ID%22%3A%20698320%2C%22Login%20ID%22%3A%201604561%2C%22Is%20Internal%20Event%22%3A%20true%2C%22App%20Theme%22%3A%20%22Dark%22%2C%22Viewport%20Width%22%3A%201660%2C%22Viewport%20Height%22%3A%20894%7D; intercom-session-ghwe0see=bzRzODRVdG9KOUh4RW44ZDNUQ0Z1VE9OSU1oWk92bUt1ZEZMYzNHWnBCMDFQd2N3MkVQWTU3ZlFWNXNHQ0VNZS0tZ3dHblEwUUIwQlZieGJ3ekwzbW94Zz09--3c5fac08798af57b5f4bff6bed4335c107588c6a; __cf_bm=kPolwB6GfmCznZdDx67XN2VD_BhS_sn4Nd.40Oagz3o-1669934841-0-AUKFXZFv0YZEK5JmdcZvyEtjCNvF3bl9KEM63D69mACL9md66zd0JbTbVp/sVToyGFSTaYBt5ppVUHVm06VhADc=; _gat=1; mp_c9915db416db9acd76b2f6823b3c3d9f_mixpanel=%7B%22distinct_id%22%3A%20%221604561_415272%22%2C%22%24device_id%22%3A%20%221843dc512e6b8a-09905823f1d8d7-18525635-1fa400-1843dc512e7f88%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fapp.sproutsocial.com%2Flogin%2Fsalesforceframe%2F%3Fdstn%3D%2Fsalesforceframe%2Fclient%2Flinkedin%2FkZnBS7o9PZ%2Fthread%2F6904742%2Flu%3Aurn%3Ali%3Ashare%3A6959231151471288320%2F%3Fcomment_guid%3Dlc%3A6960593135974420480%22%2C%22%24initial_referring_domain%22%3A%20%22app.sproutsocial.com%22%2C%22%24user_id%22%3A%20%221604561_415272%22%2C%22Customer%20ID%22%3A%20415272%2C%22Group%20ID%22%3A%20698320%2C%22Login%20ID%22%3A%201604561%2C%22Is%20Internal%20Event%22%3A%20true%2C%22App%20Theme%22%3A%20%22Dark%22%2C%22Viewport%20Width%22%3A%201680%2C%22Viewport%20Height%22%3A%20914%7D; intercom-session-ohku3rnz=dEF0SmdOZUtlT1Y4ZEdJeklkSVZsWFc0clRpWTdMTlpsTmhrMWhDaldRM21IeDlJZkVaMHdtdUdGY0h4WDdyZC0tZmxNbEpyQVNyMVRtVDVGQXRpbGNPdz09--8353af5308dd7ab1017545b76c7235c080b50d73",
      "Referer": "https://app.sproutsocial.com/messages/smart",
      "Referrer-Policy": "strict-origin-when-cross-origin"
    },
    "body": "completed=true&before=1669935584&since=1662102000&bucket=1w&nwk=2272968&nwk=2272918&nwk=2828299&nwk=2272919&nwk=2934043&nwk=2759111&nwk=7092967&nwk=3713890&nwk=2759104&nwk=2309127&nwk=3424571&nwk=2807988&nwk=3713355&nwk=3987464&nwk=2998147&nwk=2288384&nwk=3834852&nwk=2288363&nwk=2288374&nwk=2759108&nwk=2764751&nwk=2510178&nwk=3713359&nwk=2288375&nwk=2759109&nwk=2288365&nwk=3031470&nwk=2764754&nwk=2318935&nwk=3321014&nwk=3987416&nwk=3102776&nwk=3713904&nwk=2760612&nwk=5066865&nwk=2272920&nwk=6376923&msg_type=mention&inbox_sort=reverse_chron&allowlist_inbox=true&completion_status=completed&completion_status=uncompleted",
    "method": "POST"
  });

  const {data} = await response.json();

  const stats = (await import("../../dist/stats.json")) as unknown as Stats;
  const content = renderToString(
    <ConfigContext.Provider value={config}>
      <App />
    </ConfigContext.Provider>,
  );
  return html({ stats, content, config, data });
}
